export const Countries = {
  afghanistan: { name: "Afghanistan", code: "AF", phoneCode: "+93" },
  albania: { name: "Albania", code: "AL", phoneCode: "+355" },
  algeria: { name: "Algeria", code: "DZ", phoneCode: "+213" },
  andorra: { name: "Andorra", code: "AD", phoneCode: "+376" },
  angola: { name: "Angola", code: "AO", phoneCode: "+244" },
  antiguaAndBarbuda: {
    name: "Antigua and Barbuda",
    code: "AG",
    phoneCode: "+1268"
  },
  argentina: { name: "Argentina", code: "AR", phoneCode: "+54" },
  armenia: { name: "Armenia", code: "AM", phoneCode: "+374" },
  australia: { name: "Australia", code: "AU", phoneCode: "+61" },
  austria: { name: "Austria", code: "AT", phoneCode: "+43" },
  azerbaijan: { name: "Azerbaijan", code: "AZ", phoneCode: "+994" },
  bahamas: { name: "Bahamas", code: "BS", phoneCode: "+1242" },
  bahrain: { name: "Bahrain", code: "BH", phoneCode: "+973" },
  bangladesh: { name: "Bangladesh", code: "BD", phoneCode: "+880" },
  barbados: { name: "Barbados", code: "BB", phoneCode: "+1246" },
  belarus: { name: "Belarus", code: "BY", phoneCode: "+375" },
  belgium: { name: "Belgium", code: "BE", phoneCode: "+32" },
  belize: { name: "Belize", code: "BZ", phoneCode: "+501" },
  benin: { name: "Benin", code: "BJ", phoneCode: "+229" },
  bhutan: { name: "Bhutan", code: "BT", phoneCode: "+975" },
  bolivia: { name: "Bolivia", code: "BO", phoneCode: "+591" },
  bosniaAndHerzegovina: {
    name: "Bosnia and Herzegovina",
    code: "BA",
    phoneCode: "+387"
  },
  botswana: { name: "Botswana", code: "BW", phoneCode: "+267" },
  brazil: { name: "Brazil", code: "BR", phoneCode: "+55" },
  brunei: { name: "Brunei", code: "BN", phoneCode: "+673" },
  bulgaria: { name: "Bulgaria", code: "BG", phoneCode: "+359" },
  burkinaFaso: { name: "Burkina Faso", code: "BF", phoneCode: "+226" },
  burundi: { name: "Burundi", code: "BI", phoneCode: "+257" },
  cambodia: { name: "Cambodia", code: "KH", phoneCode: "+855" },
  cameroon: { name: "Cameroon", code: "CM", phoneCode: "+237" },
  canada: { name: "Canada", code: "CA", phoneCode: "+1" },
  capeVerde: { name: "Cape Verde", code: "CV", phoneCode: "+238" },
  centralAfricanRepublic: {
    name: "Central African Republic",
    code: "CF",
    phoneCode: "+236"
  },
  chad: { name: "Chad", code: "TD", phoneCode: "+235" },
  chile: { name: "Chile", code: "CL", phoneCode: "+56" },
  china: { name: "China", code: "CN", phoneCode: "+86" },
  colombia: { name: "Colombia", code: "CO", phoneCode: "+57" },
  comoros: { name: "Comoros", code: "KM", phoneCode: "+269" },
  congo: { name: "Congo", code: "CG", phoneCode: "+242" },
  costaRica: { name: "Costa Rica", code: "CR", phoneCode: "+506" },
  croatia: { name: "Croatia", code: "HR", phoneCode: "+385" },
  cuba: { name: "Cuba", code: "CU", phoneCode: "+53" },
  cyprus: { name: "Cyprus", code: "CY", phoneCode: "+357" },
  czechRepublic: { name: "Czech Republic", code: "CZ", phoneCode: "+420" },
  democraticRepublicOfCongo: {
    name: "Democratic Republic of Congo",
    code: "CD",
    phoneCode: "+243"
  },
  denmark: { name: "Denmark", code: "DK", phoneCode: "+45" },
  djibouti: { name: "Djibouti", code: "DJ", phoneCode: "+253" },
  dominica: { name: "Dominica", code: "DM", phoneCode: "+1767" },
  dominicanRepublic: {
    name: "Dominican Republic",
    code: "DO",
    phoneCode: "+1849"
  },
  eastTimor: { name: "East Timor", code: "TL", phoneCode: "+670" },
  ecuador: { name: "Ecuador", code: "EC", phoneCode: "+593" },
  egypt: { name: "Egypt", code: "EG", phoneCode: "+20" },
  elSalvador: { name: "El Salvador", code: "SV", phoneCode: "+503" },
  equatorialGuinea: {
    name: "Equatorial Guinea",
    code: "GQ",
    phoneCode: "+240"
  },
  eritrea: { name: "Eritrea", code: "ER", phoneCode: "+291" },
  estonia: { name: "Estonia", code: "EE", phoneCode: "+372" },
  ethiopia: { name: "Ethiopia", code: "ET", phoneCode: "+251" },
  fiji: { name: "Fiji", code: "FJ", phoneCode: "+679" },
  finland: { name: "Finland", code: "FI", phoneCode: "+358" },
  france: { name: "France", code: "FR", phoneCode: "+33" },
  gabon: { name: "Gabon", code: "GA", phoneCode: "+241" },
  gambia: { name: "Gambia", code: "GM", phoneCode: "+220" },
  georgia: { name: "Georgia", code: "GE", phoneCode: "+995" },
  germany: { name: "Germany", code: "DE", phoneCode: "+49" },
  ghana: { name: "Ghana", code: "GH", phoneCode: "+233" },
  greece: { name: "Greece", code: "GR", phoneCode: "+30" },
  grenada: { name: "Grenada", code: "GD", phoneCode: "+1473" },
  guatemala: { name: "Guatemala", code: "GT", phoneCode: "+502" },
  guinea: { name: "Guinea", code: "GN", phoneCode: "+224" },
  guineaBissau: { name: "Guinea-Bissau", code: "GW", phoneCode: "+245" },
  guyana: { name: "Guyana", code: "GY", phoneCode: "+592" },
  haiti: { name: "Haiti", code: "HT", phoneCode: "+509" },
  honduras: { name: "Honduras", code: "HN", phoneCode: "+504" },
  hungary: { name: "Hungary", code: "HU", phoneCode: "+36" },
  iceland: { name: "Iceland", code: "IS", phoneCode: "+354" },
  india: { name: "India", code: "IN", phoneCode: "+91" },
  indonesia: { name: "Indonesia", code: "ID", phoneCode: "+62" },
  iran: { name: "Iran", code: "IR", phoneCode: "+98" },
  iraq: { name: "Iraq", code: "IQ", phoneCode: "+964" },
  ireland: { name: "Ireland", code: "IE", phoneCode: "+353" },
  israel: { name: "Israel", code: "IL", phoneCode: "+972" },
  italy: { name: "Italy", code: "IT", phoneCode: "+39" },
  ivoryCoast: { name: "Ivory Coast", code: "CI", phoneCode: "+225" },
  jamaica: { name: "Jamaica", code: "JM", phoneCode: "+1876" },
  japan: { name: "Japan", code: "JP", phoneCode: "+81" },
  jordan: { name: "Jordan", code: "JO", phoneCode: "+962" },
  kazakhstan: { name: "Kazakhstan", code: "KZ", phoneCode: "+7" },
  kenya: { name: "Kenya", code: "KE", phoneCode: "+254" },
  kiribati: { name: "Kiribati", code: "KI", phoneCode: "+686" },
  kuwait: { name: "Kuwait", code: "KW", phoneCode: "+965" },
  kyrgyzstan: { name: "Kyrgyzstan", code: "KG", phoneCode: "+996" },
  laos: { name: "Laos", code: "LA", phoneCode: "+856" },
  latvia: { name: "Latvia", code: "LV", phoneCode: "+371" },
  lebanon: { name: "Lebanon", code: "LB", phoneCode: "+961" },
  lesotho: { name: "Lesotho", code: "LS", phoneCode: "+266" },
  liberia: { name: "Liberia", code: "LR", phoneCode: "+231" },
  libya: { name: "Libya", code: "LY", phoneCode: "+218" },
  liechtenstein: { name: "Liechtenstein", code: "LI", phoneCode: "+423" },
  lithuania: { name: "Lithuania", code: "LT", phoneCode: "+370" },
  luxembourg: { name: "Luxembourg", code: "LU", phoneCode: "+352" },
  madagascar: { name: "Madagascar", code: "MG", phoneCode: "+261" },
  malawi: { name: "Malawi", code: "MW", phoneCode: "+265" },
  malaysia: { name: "Malaysia", code: "MY", phoneCode: "+60" },
  maldives: { name: "Maldives", code: "MV", phoneCode: "+960" },
  mali: { name: "Mali", code: "ML", phoneCode: "+223" },
  malta: { name: "Malta", code: "MT", phoneCode: "+356" },
  marshallIslands: { name: "Marshall Islands", code: "MH", phoneCode: "+692" },
  mauritania: { name: "Mauritania", code: "MR", phoneCode: "+222" },
  mauritius: { name: "Mauritius", code: "MU", phoneCode: "+230" },
  mexico: { name: "Mexico", code: "MX", phoneCode: "+52" },
  micronesia: { name: "Micronesia", code: "FM", phoneCode: "+691" },
  moldova: { name: "Moldova", code: "MD", phoneCode: "+373" },
  monaco: { name: "Monaco", code: "MC", phoneCode: "+377" },
  mongolia: { name: "Mongolia", code: "MN", phoneCode: "+976" },
  montenegro: { name: "Montenegro", code: "ME", phoneCode: "+382" },
  morocco: { name: "Morocco", code: "MA", phoneCode: "+212" },
  mozambique: { name: "Mozambique", code: "MZ", phoneCode: "+258" },
  myanmar: { name: "Myanmar", code: "MM", phoneCode: "+95" },
  namibia: { name: "Namibia", code: "NA", phoneCode: "+264" },
  nauru: { name: "Nauru", code: "NR", phoneCode: "+674" },
  nepal: { name: "Nepal", code: "NP", phoneCode: "+977" },
  netherlands: { name: "Netherlands", code: "NL", phoneCode: "+31" },
  newZealand: { name: "New Zealand", code: "NZ", phoneCode: "+64" },
  nicaragua: { name: "Nicaragua", code: "NI", phoneCode: "+505" },
  niger: { name: "Niger", code: "NE", phoneCode: "+227" },
  nigeria: { name: "Nigeria", code: "NG", phoneCode: "+234" },
  northKorea: { name: "North Korea", code: "KP", phoneCode: "+850" },
  northMacedonia: { name: "North Macedonia", code: "MK", phoneCode: "+389" },
  norway: { name: "Norway", code: "NO", phoneCode: "+47" },
  oman: { name: "Oman", code: "OM", phoneCode: "+968" },
  pakistan: { name: "Pakistan", code: "PK", phoneCode: "+92" },
  palau: { name: "Palau", code: "PW", phoneCode: "+680" },
  palestine: { name: "Palestine", code: "PS", phoneCode: "+970" },
  panama: { name: "Panama", code: "PA", phoneCode: "+507" },
  papuaNewGuinea: { name: "Papua New Guinea", code: "PG", phoneCode: "+675" },
  paraguay: { name: "Paraguay", code: "PY", phoneCode: "+595" },
  peru: { name: "Peru", code: "PE", phoneCode: "+51" },
  philippines: { name: "Philippines", code: "PH", phoneCode: "+63" },
  poland: { name: "Poland", code: "PL", phoneCode: "+48" },
  portugal: { name: "Portugal", code: "PT", phoneCode: "+351" },
  qatar: { name: "Qatar", code: "QA", phoneCode: "+974" },
  romania: { name: "Romania", code: "RO", phoneCode: "+40" },
  russia: { name: "Russia", code: "RU", phoneCode: "+7" },
  rwanda: { name: "Rwanda", code: "RW", phoneCode: "+250" },
  saintKittsAndNevis: {
    name: "Saint Kitts and Nevis",
    code: "KN",
    phoneCode: "+1869"
  },
  saintLucia: { name: "Saint Lucia", code: "LC", phoneCode: "+1758" },
  saintVincentAndTheGrenadines: {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    phoneCode: "+1784"
  },
  samoa: { name: "Samoa", code: "WS", phoneCode: "+685" },
  sanMarino: { name: "San Marino", code: "SM", phoneCode: "+378" },
  saoTomeAndPrincipe: {
    name: "Sao Tome and Principe",
    code: "ST",
    phoneCode: "+239"
  },
  saudiArabia: { name: "Saudi Arabia", code: "SA", phoneCode: "+966" },
  senegal: { name: "Senegal", code: "SN", phoneCode: "+221" },
  serbia: { name: "Serbia", code: "RS", phoneCode: "+381" },
  seychelles: { name: "Seychelles", code: "SC", phoneCode: "+248" },
  sierraLeone: { name: "Sierra Leone", code: "SL", phoneCode: "+232" },
  singapore: { name: "Singapore", code: "SG", phoneCode: "+65" },
  slovakia: { name: "Slovakia", code: "SK", phoneCode: "+421" },
  slovenia: { name: "Slovenia", code: "SI", phoneCode: "+386" },
  solomonIslands: { name: "Solomon Islands", code: "SB", phoneCode: "+677" },
  somalia: { name: "Somalia", code: "SO", phoneCode: "+252" },
  southAfrica: { name: "South Africa", code: "ZA", phoneCode: "+27" },
  southKorea: { name: "South Korea", code: "KR", phoneCode: "+82" },
  southSudan: { name: "South Sudan", code: "SS", phoneCode: "+211" },
  spain: { name: "Spain", code: "ES", phoneCode: "+34" },
  sriLanka: { name: "Sri Lanka", code: "LK", phoneCode: "+94" },
  sudan: { name: "Sudan", code: "SD", phoneCode: "+249" },
  suriname: { name: "Suriname", code: "SR", phoneCode: "+597" },
  swaziland: { name: "Swaziland", code: "SZ", phoneCode: "+268" },
  sweden: { name: "Sweden", code: "SE", phoneCode: "+46" },
  switzerland: { name: "Switzerland", code: "CH", phoneCode: "+41" },
  syria: { name: "Syria", code: "SY", phoneCode: "+963" },
  tajikistan: { name: "Tajikistan", code: "TJ", phoneCode: "+992" },
  tanzania: { name: "Tanzania", code: "TZ", phoneCode: "+255" },
  thailand: { name: "Thailand", code: "TH", phoneCode: "+66" },
  togo: { name: "Togo", code: "TG", phoneCode: "+228" },
  tonga: { name: "Tonga", code: "TO", phoneCode: "+676" },
  trinidadAndTobago: {
    name: "Trinidad and Tobago",
    code: "TT",
    phoneCode: "+1868"
  },
  tunisia: { name: "Tunisia", code: "TN", phoneCode: "+216" },
  turkey: { name: "Turkey", code: "TR", phoneCode: "+90" },
  turkmenistan: { name: "Turkmenistan", code: "TM", phoneCode: "+993" },
  tuvalu: { name: "Tuvalu", code: "TV", phoneCode: "+688" },
  uganda: { name: "Uganda", code: "UG", phoneCode: "+256" },
  ukraine: { name: "Ukraine", code: "UA", phoneCode: "+380" },
  unitedArabEmirates: {
    name: "United Arab Emirates",
    code: "AE",
    phoneCode: "+971"
  },
  unitedKingdom: { name: "United Kingdom", code: "GB", phoneCode: "+44" },
  unitedStates: { name: "United States", code: "US", phoneCode: "+1" },
  uruguay: { name: "Uruguay", code: "UY", phoneCode: "+598" },
  uzbekistan: { name: "Uzbekistan", code: "UZ", phoneCode: "+998" },
  vanuatu: { name: "Vanuatu", code: "VU", phoneCode: "+678" },
  vaticanCity: { name: "Vatican City", code: "VA", phoneCode: "+379" },
  venezuela: { name: "Venezuela", code: "VE", phoneCode: "+58" },
  vietnam: { name: "Vietnam", code: "VN", phoneCode: "+84" },
  yemen: { name: "Yemen", code: "YE", phoneCode: "+967" },
  zambia: { name: "Zambia", code: "ZM", phoneCode: "+260" },
  zimbabwe: { name: "Zimbabwe", code: "ZW", phoneCode: "+263" }
} as const

export const CountryCodes = Object.keys(Countries) as (keyof typeof Countries)[]

export type CountryNames = (typeof Countries)[keyof typeof Countries]["name"]

export type CountryNameKey = keyof typeof Countries

export type CountryCode = (typeof Countries)[keyof typeof Countries]["code"]

export type CountryPhoneCode =
  (typeof Countries)[keyof typeof Countries]["phoneCode"]

/// get country by code | Big O(N)
export const getCountryByCode = (code: CountryCode) =>
  Object.values(Countries).find((country) => country.code === code)

// get country by phone code | Big O(N)
export const getCountryByPhoneCode = (phoneCode: CountryPhoneCode) =>
  Object.values(Countries).find((country) => country.phoneCode === phoneCode)

// get country by name-key | Big O(1) [Recommended]
export const getCountryByName = (name: CountryNameKey) => Countries[name]

// get country by name | Big O(N)
export const getCountryByNameValue = (name: CountryNames) =>
  Object.values(Countries).find((country) => country.name === name)
