name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run test coverage
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate coverage badge
        run: npx covgen badge

      - name: Update README with coverage badge
        run: |
          COVERAGE_BADGE=$(cat coverage/badge.svg)
          sed -i 's|<img src=".*" alt="Coverage Badge"/>|'"$COVERAGE_BADGE"'|' README.md

      - name: Generate test result badge
        run: npx vitest-badge-gen

      - name: Update README with test result badge
        run: |
          TEST_BADGE=$(cat test-result/badge.svg)
          sed -i 's|<img src=".*" alt="Test Result Badge"/>|'"$TEST_BADGE"'|' README.md
