name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run test coverage
        run: npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate coverage badge
        run: |
          npx covgen badge
          ls -R coverage  # Check contents of the coverage folder

      - name: Generate test result badge
        run: node scripts/generate-badges.cjs

      - name: Update README with coverage badge
        run: |
          if [ -f coverage/badge.svg ]; then
            COVERAGE_BADGE=$(cat coverage/badge.svg)
            sed -i 's|<img src=".*" alt="Coverage Badge"/>|'"$COVERAGE_BADGE"'|' README.md
          else
            echo "Coverage badge not found"
          fi

      - name: Update README with coverage badge
        run: |
          if [ -f coverage/badge.svg ]; then
            # Replace the badge placeholder in README.md with actual badge content
            COVERAGE_BADGE=$(cat coverage/badge.svg)
            # Use '#' as delimiter and insert the badge safely into README.md
            sed -i 's#<img src=".*" alt="Coverage Badge"/>#'"$COVERAGE_BADGE"'#' README.md
          else
            echo "Coverage badge not found"
          fi
