name: Run Linters

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check for node_modules directory
        run: |
          if [ -d "node_modules" ]; then
            echo "node_modules directory found. This shouldn't be in there at all."
            exit 1
          fi

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint
